### PR TITLE
option to set custom service name, resolves #19

### LINKED ISSUE #19: Set custom service name
Option to provide custom service name would make more meaningful admin page of consul web ui.

We have multiple services, but when i open web ui, it is not possible to understand service's purpose without inspecting logs. Is there any limitations why variable SERVICE_NAME is constant?

### PR DESCRIPTION
**Pull request by deedarb**
also updated vert.x to 3.9.1

### CODE REVIEW

**Comment by romalev** [comment]
Wow - first contribution! Change looks great to me @deedarb! Just out of curious - are you using this implementation in prod ?

There's one thing I'd like to point out: Starting from 4.x.x cluster management SPI is going to get changed so this implementation must reflect the new SPI contract. Let me know if you're interested in contributing to this project.

**Comment by romalev** [comment]
And also - I am going to merge this PR and release new `3.9.1` version to mvn central.

**Comment by deedarb** [comment]
yes, using for prod, i extended ConsulClusterManager class to add this feature (serviceName) and already using it in prod :) I will switch back to ConsulClusterManager after new version released, also i found that after killing app, vert.x service is not leaving cluster. To support graceful node leave i added 

    private void registerStopWatch() {
		stopWatch = Watch.events("stop", appContext.getVertx(), appContext.getConsulClientOptions())
			.setHandler(wr -> {
				if (wr.succeeded()) {
					for (Event event : wr.nextResult().getList()) {
						if (Objects.equals(event.getPayload(), getNodeID())) {
							log.info("got stop event from consul...stopping");
							appContext.getVertx().close();
						}
					}
				} else {
					log.error("stop watch handler error", wr.cause());
				}
			})
			.start();
	}

using node id (from web ui) i gracefully stop app by executing `./consul event -name=stop NODE_ID`

I don't know if it is a good way of implementing it in this way, but it helps to avoid unreachable vert.x node in consul.
It is my first merged PR in OSS!

**Comment by romalev** [comment]
To be frank - it's been a while since I haven't used this implementation as well as I haven't contributed anything to it -> my knowledge is a bit outdated I should say. As far as I remember normally service should get auto unregistered after some period of time once tcp check gets failed ... but this is to be double checked. 

Also new version 3.9.1 has been released (containing your change, THANKS!!!) : https://repo.maven.apache.org/maven2/io/reactiverse/consul-cluster-manager/3.9.1/

**Pull request merged**
